pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
		     def props = readProperties  file: 'read-properties/example.properties'
		     println(props['key1'])
                }
            }
        }
    }
}

